# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=posts.models.upload_location, verbose_name='Изображение')),
                ('photo_medium', models.ImageField(blank=True, null=True, upload_to=posts.models.upload_location, verbose_name='Изображение среднее')),
                ('photo_thumb', models.ImageField(blank=True, null=True, upload_to=posts.models.upload_location, verbose_name='Изображение обычное')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
