# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20171129_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo_medium',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_thumb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
