# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20171129_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo_medium',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.upload_location, verbose_name='Изображение среднее'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_thumb',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.upload_location, verbose_name='Изображение обычное'),
        ),
    ]
